services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    ports:
      - "8000:8000"
      - "5000:5000"
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
    networks:
      - backend
  mongo:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"   # host:container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db  # persist data
    networks:
      - backend
  mongo-express:   # Web UI for MongoDB (optional but useful)
    image: mongo-express:1.0.0-alpha
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    depends_on:
      - mongo
    networks:
      - backend
networks:
  backend:
volumes:
  mongo_data: